from django.urls import path

from .views import (
    dashboard,
    login_view,
    logout_view,
    create_company,
    company_list,
    company_detail,
    update_company,
    delete_company,
    employee_list,
    create_employee,
    employee_detail,
    update_employee,
    delete_employee,
    create_task,
    task_list,
    task_detail,
    update_task,
    delete_task,
    export_companies_csv,
    import_companies_csv,
    download_company_template,
)

urlpatterns = [

    path(
        '',
        dashboard,
        name='dashboard'
    ),

    path(
        'login/',
        login_view,
        name='login'
    ),

    path(
        'logout/',
        logout_view,
        name='logout'
    ),
    path(
        'companies/create/',
        create_company,
        name='create_company'
    ),
    path(
        'companies/',
        company_list,
        name='company_list'
    ),
    path(
        'companies/import/',
        import_companies_csv,
        name='import_companies_csv'
    ),
    path(
        'companies/template/',
        download_company_template,
        name='download_company_template'
    ),
    path(
        'companies/<slug:slug>/',
        company_detail,
        name='company_detail'
    ),
    path(
        'companies/<slug:slug>/update/',
        update_company,
        name='update_company'
    ),
    path(
        'companies/<slug:slug>/delete/',
        delete_company,
        name='delete_company'
    ),
    path(
        'employees/',
        employee_list,
        name='employee_list'
    ),
    path(
        'employees/create/',
        create_employee,
        name='create_employee'
    ),
    path(
        'employees/<int:id>/',
        employee_detail,
        name='employee_detail'
    ),
    path(
        'employees/<int:id>/update/',
        update_employee,
        name='update_employee'
    ),
    path(
        'employees/<int:id>/delete/',
        delete_employee,
        name='delete_employee'
    ),
    path(
        'tasks/create/',
        create_task,
        name='create_task'
    ),
    path(
        'tasks/',
        task_list,
        name='task_list'
    ),
    path(
        'tasks/<int:id>/',
        task_detail,
        name='task_detail'
    ),
    path(
        'tasks/<int:id>/update/',
        update_task,
        name='update_task'
    ),
    path(
        'tasks/<int:id>/delete/',
        delete_task,
        name='delete_task'
    ),
    path(
        'export-companies/',
        export_companies_csv,
        name='export_companies_csv'
    ),
]