from django.urls import path
from django.contrib.auth import views as auth_views

from .views import (
    dashboard,
    login_view,
    logout_view,
    create_company,
    company_list,
    update_company,
    delete_company,
    employee_list,
    create_employee,
    update_employee,
    delete_employee,
    create_task,
    task_list,
    update_task,
    delete_task,
    export_companies_csv,
    import_companies_csv,
    download_company_template,
    CustomPasswordResetView,
    CustomPasswordResetDoneView,
    my_profile,
    ajax_validate,
    access_role_list,
    create_access_role,
    update_access_role,
    manage_role_permissions,
    ajax_get_representatives,
    ajax_get_companies,
)

urlpatterns = [

    path(
        '',
        dashboard,
        name='dashboard'
    ),
    
    path(
        'profile/',
        my_profile,
        name='my_profile'
    ),
    
    path(
        'login/',
        login_view,
        name='login'
    ),

    path(
        'logout/',
        logout_view,
        name='logout'
    ),
    path(
        'companies/create/',
        create_company,
        name='create_company'
    ),
    path(
        'companies/',
        company_list,
        name='company_list'
    ),
    path(
        'companies/import/',
        import_companies_csv,
        name='import_companies_csv'
    ),
    path(
        'companies/template/',
        download_company_template,
        name='download_company_template'
    ),
    path(
        'companies/<slug:slug>/update/',
        update_company,
        name='update_company'
    ),
    path(
        'companies/<slug:slug>/delete/',
        delete_company,
        name='delete_company'
    ),
    path(
        'employees/',
        employee_list,
        name='employee_list'
    ),
    path(
        'employees/create/',
        create_employee,
        name='create_employee'
    ),
    path(
        'employees/<int:id>/update/',
        update_employee,
        name='update_employee'
    ),
    path(
        'employees/<int:id>/delete/',
        delete_employee,
        name='delete_employee'
    ),
    path(
        'tasks/create/',
        create_task,
        name='create_task'
    ),
    path(
        'tasks/',
        task_list,
        name='task_list'
    ),
    path(
        'tasks/<int:id>/update/',
        update_task,
        name='update_task'
    ),
    path(
        'tasks/<int:id>/delete/',
        delete_task,
        name='delete_task'
    ),
    path(
        'export-companies/',
        export_companies_csv,
        name='export_companies_csv'
    ),
    path(
        'password-reset/',
        CustomPasswordResetView.as_view(
            template_name='password_reset.html',
            email_template_name='password_reset_email.html',
            success_url='/password-reset/done/'
        ),
        name='password_reset'
    ),

    path(
        'password-reset/done/',
        CustomPasswordResetDoneView.as_view(
            template_name='password_reset_done.html'
        ),
        name='password_reset_done'
    ),

    path(
        'reset/<uidb64>/<token>/',
        auth_views.PasswordResetConfirmView.as_view(
            template_name='password_reset_confirm.html',
            success_url='/reset-complete/'
        ),
        name='password_reset_confirm'
    ),

    path(
        'reset-complete/',
        auth_views.PasswordResetCompleteView.as_view(
            template_name='password_reset_complete.html'
        ),
        name='password_reset_complete'
    ),
    path(
        'ajax/validate/',
        ajax_validate,
        name='ajax_validate'
    ),
    path(
        "access-roles/",
        access_role_list,
        name="access_role_list",
    ),
    path(
    "access-roles/create/",
    create_access_role,
    name="create_access_role",
    ),

    path(
        "access-roles/<int:id>/update/",
        update_access_role,
        name="update_access_role",
    ),path(
    "access-roles/<int:id>/permissions/",
        manage_role_permissions,
        name="manage_role_permissions",
    ),
    path(
        'ajax/representatives/',
        ajax_get_representatives,
        name='ajax_get_representatives'
    ),
    path(
        'ajax/companies/',
        ajax_get_companies,
        name='ajax_get_companies'
    ),
]