# Generated by Django 6.0.5 on 2026-06-16 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0003_task'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='deadline',
            field=models.DateTimeField(),
        ),
    ]
