# Generated by Django 6.0.5 on 2026-06-17 06:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0006_alter_company_phone_alter_employee_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='reporting_manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='representatives', to='crm.employee'),
        ),
        migrations.AddField(
            model_name='employee',
            name='role',
            field=models.CharField(choices=[('manager', 'Manager'), ('representative', 'Representative')], default=1, max_length=20),
            preserve_default=False,
        ),
    ]
