# Generated by Django 6.0.5 on 2026-06-19 07:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0007_employee_reporting_manager_employee_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='manager',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'manager'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='companies', to='crm.employee'),
        ),
    ]
