# Generated by Django 6.0.5 on 2026-06-19 12:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0010_alter_employee_company'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='company',
        ),
    ]
