# Generated by Django 6.0.5 on 2026-06-29 09:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0012_permission_role_rolepermission'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='new_role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employees', to='crm.role'),
        ),
    ]
