# Generated by Django 6.0.5 on 2026-06-30 05:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0013_employee_new_role'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='new_role',
            new_name='access_role',
        ),
    ]
