# Generated by Django 6.0.5 on 2026-07-01 05:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0014_rename_new_role_employee_access_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='designation',
        ),
    ]
