# Generated by Django 6.0.5 on 2026-07-02 10:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0015_remove_employee_designation'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='assignee',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'representative'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_companies', to='crm.employee'),
        ),
    ]
